(function(){var d=null;function e(a,b,c){this.extend(e,google.maps.OverlayView);this.c=a;this.a=[];this.h=[];this.sizes=[53,56,66,78,90];this.m=[];this.J=!1;c=c||{};this.i=c.gridSize||60;this.s=c.minimumClusterSize||2;this.T=c.maxZoom||null;this.m=c.styles||[];this.ga=c.imagePath||this.$;this.fa=c.imageExtension||this.Z;this.Y=!0;void 0!=c.zoomOnClick&&(this.Y=c.zoomOnClick);this.C=!1;void 0!=c.averageCenter&&(this.C=c.averageCenter);k(this);this.setMap(a);this.U=this.c.getZoom();var f=this;google.maps.event.addListener(this.c,"zoom_changed",
function(){var a=f.c.getZoom();f.U!=a&&(f.U=a,f.u())});google.maps.event.addListener(this.c,"idle",function(){f.l()});b&&b.length&&this.L(b,!1)}d=e.prototype;d.$="http://google-maps-utility-library-v3.googlecode.com/svn/trunk/markerclusterer/images/m";d.Z="png";d.extend=function(a,b){return function(a){for(var b in a.prototype)this.prototype[b]=a.prototype[b];return this}.apply(a,[b])};d.onAdd=function(){this.J||(this.J=!0,l(this))};d.draw=function(){};
function k(a){if(!a.m.length)for(var b=0,c;c=a.sizes[b];b++)a.m.push({url:a.ga+(b+1)+"."+a.fa,height:c,width:c})}d.ba=function(){for(var a=this.w(),b=new google.maps.LatLngBounds,c=0,f;f=a[c];c++)b.extend(f.getPosition());this.c.fitBounds(b)};d.I=function(){return this.m};d.w=function(){return this.a};d.ea=function(){return this.a.length};d.la=function(a){this.T=a};d.S=function(){return this.T};
d.O=function(a,b){for(var c=0,f=a.length,g=f;0!==g;)g=parseInt(g/10,10),c++;c=Math.min(c,b);return{text:f,index:c}};d.ja=function(a){this.O=a};d.P=function(){return this.O};d.L=function(a,b){for(var c=0,f;f=a[c];c++)q(this,f);b||this.l()};function q(a,b){b.D=!1;b.draggable&&google.maps.event.addListener(b,"dragend",function(){b.D=!1;a.V()});a.a.push(b)}d.B=function(a,b){q(this,a);b||this.l()};
function r(a,b){var c=-1;if(a.a.indexOf)c=a.a.indexOf(b);else for(var f=0,g;g=a.a[f];f++)if(g==b){c=f;break}if(-1==c)return!1;b.setMap(null);a.a.splice(c,1);return!0}d.ha=function(a,b){var c=r(this,a);return!b&&c?(this.u(),this.l(),!0):!1};d.ia=function(a,b){for(var c=!1,f=0,g;g=a[f];f++)g=r(this,g),c=c||g;if(!b&&c)return this.u(),this.l(),!0};d.da=function(){return this.h.length};d.getMap=function(){return this.c};d.setMap=function(a){this.c=a};d.R=function(){return this.i};
d.ka=function(a){this.i=a};d.H=function(a){var b=this.getProjection(),c=new google.maps.LatLng(a.getNorthEast().lat(),a.getNorthEast().lng()),f=new google.maps.LatLng(a.getSouthWest().lat(),a.getSouthWest().lng()),c=b.fromLatLngToDivPixel(c);c.x+=this.i;c.y-=this.i;f=b.fromLatLngToDivPixel(f);f.x-=this.i;f.y+=this.i;c=b.fromDivPixelToLatLng(c);b=b.fromDivPixelToLatLng(f);a.extend(c);a.extend(b);return a};d.aa=function(){this.u(!0);this.a=[]};
d.u=function(a){for(var b=0,c;c=this.h[b];b++)c.remove();for(b=0;c=this.a[b];b++)c.D=!1,a&&c.setMap(null);this.h=[]};d.V=function(){var a=this.h.slice();this.h.length=0;this.u();this.l();window.setTimeout(function(){for(var b=0,c;c=a[b];b++)c.remove()},0)};d.l=function(){l(this)};
function l(a){if(a.J)for(var b=new google.maps.LatLngBounds(a.c.getBounds().getSouthWest(),a.c.getBounds().getNorthEast()),b=a.H(b),c=0,f;f=a.a[c];c++)if(!f.D&&b.contains(f.getPosition())){for(var g=a,v=4E4,n=null,w=0,m=void 0;m=g.h[w];w++){var h=m.getCenter();if(h){var p=f.getPosition();if(h&&p)var x=(p.lat()-h.lat())*Math.PI/180,y=(p.lng()-h.lng())*Math.PI/180,h=Math.sin(x/2)*Math.sin(x/2)+Math.cos(h.lat()*Math.PI/180)*Math.cos(p.lat()*Math.PI/180)*Math.sin(y/2)*Math.sin(y/2),h=12742*Math.atan2(Math.sqrt(h),
Math.sqrt(1-h));else h=0;h<v&&(v=h,n=m)}}n&&n.N.contains(f.getPosition())?n.B(f):(m=new t(g),m.B(f),g.h.push(m))}}function t(a){this.o=a;this.c=a.getMap();this.i=a.R();this.s=a.s;this.C=a.C;this.f=null;this.a=[];this.N=null;this.v=new u(this,a.I())}d=t.prototype;
d.B=function(a){var b;a:if(this.a.indexOf)b=-1!=this.a.indexOf(a);else{b=0;for(var c;c=this.a[b];b++)if(c==a){b=!0;break a}b=!1}if(b)return!1;this.f?this.C&&(c=this.a.length+1,b=(this.f.lat()*(c-1)+a.getPosition().lat())/c,c=(this.f.lng()*(c-1)+a.getPosition().lng())/c,this.f=new google.maps.LatLng(b,c),z(this)):(this.f=a.getPosition(),z(this));a.D=!0;this.a.push(a);b=this.a.length;b<this.s&&a.getMap()!=this.c&&a.setMap(this.c);if(b==this.s)for(c=0;c<b;c++)this.a[c].setMap(null);b>=this.s&&a.setMap(null);
a=this.c.getZoom();if((b=this.o.S())&&a>b)for(a=0;b=this.a[a];a++)b.setMap(this.c);else this.a.length<this.s?A(this.v):(b=this.o.P()(this.a,this.o.I().length),this.v.setCenter(this.f),a=this.v,a.K=b,a.b&&(a.b.innerHTML=b.text),b=Math.max(0,a.K.index-1),b=Math.min(a.m.length-1,b),b=a.m[b],a.ma=b.url,a.j=b.height,a.A=b.width,a.W=b.textColor,a.g=b.anchor,a.X=b.textSize,a.M=b.backgroundPosition,this.v.show());return!0};
d.getBounds=function(){for(var a=new google.maps.LatLngBounds(this.f,this.f),b=this.w(),c=0,f;f=b[c];c++)a.extend(f.getPosition());return a};d.remove=function(){this.v.remove();this.a.length=0;delete this.a};d.ca=function(){return this.a.length};d.w=function(){return this.a};d.getCenter=function(){return this.f};function z(a){var b=new google.maps.LatLngBounds(a.f,a.f);a.N=a.o.H(b)}d.getMap=function(){return this.c};
function u(a,b){a.o.extend(u,google.maps.OverlayView);this.m=b;this.G=a;this.f=null;this.c=a.getMap();this.K=this.b=null;this.F=!1;this.setMap(this.c)}d=u.prototype;
d.onAdd=function(){this.b=document.createElement("DIV");if(this.F){var a=B(this,this.f);this.b.style.cssText=C(this,a);this.b.innerHTML=this.K.text}this.getPanes().overlayMouseTarget.appendChild(this.b);var b=this;google.maps.event.addDomListener(this.b,"click",function(a){var f=b.G.o;google.maps.event.trigger(f,"clusterclick",b.G);f.Y&&b.c.fitBounds(b.G.getBounds());a.cancelBubble=!0})};
function B(a,b){var c=a.getProjection().fromLatLngToDivPixel(b);c.x-=parseInt(a.A/2,10);c.y-=parseInt(a.j/2,10);return c}d.draw=function(){if(this.F){var a=B(this,this.f);this.b.style.top=a.y+"px";this.b.style.left=a.x+"px"}};function A(a){a.b&&(a.b.style.display="none");a.F=!1}d.show=function(){if(this.b){var a=B(this,this.f);this.b.style.cssText=C(this,a);this.b.style.display=""}this.F=!0};d.remove=function(){this.setMap(null)};
d.onRemove=function(){this.b&&this.b.parentNode&&(A(this),this.b.parentNode.removeChild(this.b),this.b=null)};d.setCenter=function(a){this.f=a};
function C(a,b){var c=[];c.push("background-image:url("+a.ma+");");c.push("background-position:"+(a.M?a.M:"0 0")+";");"object"===typeof a.g?("number"===typeof a.g[0]&&0<a.g[0]&&a.g[0]<a.j?c.push("height:"+(a.j-a.g[0])+"px; padding-top:"+a.g[0]+"px;"):c.push("height:"+a.j+"px; line-height:"+a.j+"px;"),"number"===typeof a.g[1]&&0<a.g[1]&&a.g[1]<a.A?c.push("width:"+(a.A-a.g[1])+"px; padding-left:"+a.g[1]+"px;"):c.push("width:"+a.A+"px; text-align:center;")):c.push("height:"+a.j+"px; line-height:"+a.j+
"px; width:"+a.A+"px; text-align:center;");c.push("cursor:pointer; top:"+b.y+"px; left:"+b.x+"px; color:"+(a.W?a.W:"black")+"; position:absolute; font-size:"+(a.X?a.X:11)+"px; font-family:Arial,sans-serif; font-weight:bold");return c.join("")}window.MarkerClusterer=e;e.prototype.addMarker=e.prototype.B;e.prototype.addMarkers=e.prototype.L;e.prototype.clearMarkers=e.prototype.aa;e.prototype.fitMapToMarkers=e.prototype.ba;e.prototype.getCalculator=e.prototype.P;e.prototype.getGridSize=e.prototype.R;
e.prototype.getExtendedBounds=e.prototype.H;e.prototype.getMap=e.prototype.getMap;e.prototype.getMarkers=e.prototype.w;e.prototype.getMaxZoom=e.prototype.S;e.prototype.getStyles=e.prototype.I;e.prototype.getTotalClusters=e.prototype.da;e.prototype.getTotalMarkers=e.prototype.ea;e.prototype.redraw=e.prototype.l;e.prototype.removeMarker=e.prototype.ha;e.prototype.removeMarkers=e.prototype.ia;e.prototype.resetViewport=e.prototype.u;e.prototype.repaint=e.prototype.V;e.prototype.setCalculator=e.prototype.ja;
e.prototype.setGridSize=e.prototype.ka;e.prototype.setMaxZoom=e.prototype.la;e.prototype.onAdd=e.prototype.onAdd;e.prototype.draw=e.prototype.draw;t.prototype.getCenter=t.prototype.getCenter;t.prototype.getSize=t.prototype.ca;t.prototype.getMarkers=t.prototype.w;u.prototype.onAdd=u.prototype.onAdd;u.prototype.draw=u.prototype.draw;u.prototype.onRemove=u.prototype.onRemove;})();
